if (self.CavalryLogger) { CavalryLogger.start_js(["Ofutt"]); }

__d("DistanceConstants",[],(function(a,b,c,d,e,f){e.exports={KILOMETERS_PER_MILE:1.609344,MILES_PER_KILOMETER:.621371,FEET_PER_MILE:5280,METERS_PER_MILE_APPROXIMATE:1609,METERS_PER_MILE:1609.344,METERS_PER_KILOMETER:1e3,KILOMETERS_PER_METER:.001,FEET_PER_DECIMETER:.328084,MILES_PER_METER:621371e-9,EARTH_EQUATOR_LAT_DEGREE_TO_METERS:111132,EARTH_EQUATOR_LONG_DEGREE_TO_METERS:78847,EARTH_RADIUS_KM:6371.01,EARTH_SEMI_CIRCUMFERENCE_KM:20015.11}}),null);
__d("FundraiserCampaignType",[],(function(a,b,c,d,e,f){e.exports=Object.freeze({FACEBOOK_TO_USER:1,DONATE_BUTTON_ON_PAGE:2,DONATE_BUTTON_ON_ADS:3,CHARITY_TO_USER:4,DONATE_BUTTON_ON_POST:5,USER_TO_CHARITY:6,DONATE_BUTTON_ON_LIVE_VIDEO:7,LIGHTWEIGHT_FUNDRAISER_FOR_STORY:8,PERSON_FOR_PERSON:9,CRISIS_FOR_CHARITY:10,IG_STICKER_FOR_CHARITY:11,PERSON_FOR_CAUSE:12,PROFILE_FOR_CHARITY:13,IG_CHARITY_BUSINESS_PROFILE:14,PERSON_FOR_CHARITIES_IN_CAUSE:15,IG_LIVE_FOR_CHARITY:16,IG_STANDALONE_FOR_PERSON:17})}),null);
__d("SocialGoodCharityActionsTypedLoggerLite",["Banzai","generateLiteTypedLogger"],(function(a,b,c,d,e,f){"use strict";e.exports=b("generateLiteTypedLogger")("logger:SocialGoodCharityActionsLoggerConfig")}),null);
__d("StoriesUtils",["ExecutionEnvironment"],(function(a,b,c,d,e,f){"use strict";var g=500,h={};a={cardID2ThreadID:function(a){h[a]==null&&(h[a]=window.atob(a).split(":")[2]);return h[a]},shouldResizeToViewStories:function(a){return!b("ExecutionEnvironment").canUseDOM?!1:a<g}};e.exports=a}),null);
__d("SocialGoodCharityActionsLoggingUtils",["FundraiserCampaignType","SocialGoodCharityActionsTypedLoggerLite","StoriesUtils","WebSession","getJSEnumSafe"],(function(a,b,c,d,e,f){"use strict";var g=b("SocialGoodCharityActionsTypedLoggerLite").log;function a(a,c){g(babelHelpers["extends"]({campaign_type:8,explicit_post_id:c==null?null:b("StoriesUtils").cardID2ThreadID(c),parent_event_type:"create"},a))}function c(a,c,d){g({campaign_id:c,event:a,parent_event_type:"invite",source_attributes:{session_id:b("WebSession").getId(),source_id:c,source_name:(a=d)!=null?a:"fundraiser"}})}function d(a,c,d,e){g({campaign_id:d,campaign_type:b("getJSEnumSafe")(b("FundraiserCampaignType"),e),event:a,parent_event_type:"donate",source_attributes:c})}function f(a,c,d,e,f){g({attributes:e,campaign_id:c,campaign_type:b("getJSEnumSafe")(b("FundraiserCampaignType"),f),event:a,parent_event_type:"interact",source_attributes:{source_name:d}})}e.exports={logFundraiserDonateEvent:d,logFundraiserForStoryCreateEvent:a,logFundraiserInteractEvent:f,logFundraiserInviteEvent:c}}),null);
__d("CometMapInfoButton.react",["ix","fbt","CometLazyPopoverTrigger.react","JSResource","React","TetraIcon.react","fbicon","stylex"],(function(a,b,c,d,e,f,g,h){"use strict";var i=b("JSResource")("CometMapInfoMenu.react").__setRef("CometMapInfoButton.react"),j=b("React");function a(){return j.jsx("div",{className:"oqq733wu",children:j.jsx(b("CometLazyPopoverTrigger.react"),{align:"end",popoverProps:{},popoverResource:i,position:"above",children:function(a,c){return j.jsx(b("TetraIcon.react"),{"aria-label":h._("View Map Info"),color:"tertiary",icon:b("fbicon")._(g("479176"),16),onPress:c,ref:a})}})})}e.exports=a}),null);
__d("usePaymentsCometCheckout",["CometCardedDialogLoadingState.react","JSResource","React","useCometLazyDialog"],(function(a,b,c,d,e,f){"use strict";var g=b("JSResource")("PaymentsCometCheckoutDialog.react").__setRef("usePaymentsCometCheckout"),h=b("React");c=b("React");var i=c.useCallback;function a(a){var c=a.onClose,d=babelHelpers.objectWithoutPropertiesLoose(a,["onClose"]);a=b("useCometLazyDialog")(g,function(){return h.jsx(b("CometCardedDialogLoadingState.react"),{})});var e=a[0];a=a[1];var f=i(function(){e(babelHelpers["extends"]({},d,{onClose:c}),c)},[c,d,e]);return[f,a]}e.exports=a}),null);
__d("distance",["DistanceConstants"],(function(a,b,c,d,e,f){"use strict";var g=b("DistanceConstants").EARTH_RADIUS_KM,h=b("DistanceConstants").METERS_PER_KILOMETER;function a(a,b,c,d){var e=c*Math.PI/180-a*Math.PI/180;d=d*Math.PI/180-b*Math.PI/180;b=Math.sin(e/2)*Math.sin(e/2)+Math.cos(a*Math.PI/180)*Math.cos(c*Math.PI/180)*Math.sin(d/2)*Math.sin(d/2);e=2*Math.atan2(Math.sqrt(b),Math.sqrt(1-b));a=g*e;return a*h}e.exports={haversine:a}}),null);